{"name": "переход на страницу восстановления пароля по кнопке «Восстановить пароль»", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <test_password_recovery.TestRecoveryPage object at 0x000001D7327E9CD0>\ndriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"0184e341-7c2b-4dc4-913e-9e0c4066eb40\")>\n\n    @allure.title('переход на страницу восстановления пароля по кнопке «Восстановить пароль»')\n    def test_cross_via_recovery_button(self, driver):\n        main_page = MainPage(driver)\n        main_page.open_main_page()\n        main_page.click_account_button()\n        login_page = LoginPage(driver)\n>       login_page.click_recover_password_button()\n\ntests\\test_password_recovery.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\login_page.py:44: in click_recover_password_button\n    self.wait_for_element_visible(self._RECOVER_PASSWORD_BUTTON)\npages\\base_page.py:44: in wait_for_element_visible\n    WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"0184e341-7c2b-4dc4-913e-9e0c4066eb40\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x000001D732892C00>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n..\\..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "steps": [{"name": "Открыть главную страницу Stellar Burgers", "status": "passed", "steps": [{"name": "Перейти на страницу", "status": "passed", "parameters": [{"name": "url", "value": "'https://stellarburgers.nomoreparties.site/'"}], "start": 1724618263676, "stop": 1724618267469}], "start": 1724618263676, "stop": 1724618267469}, {"name": "Клик на кнопку Личный кабинет", "status": "passed", "start": 1724618267469, "stop": 1724618267843}, {"name": "Нажать на кнопку Восстановить пароль", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\Галина\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Галина\\Documents\\Yandex_praktikum\\Diplom\\Diplom_3\\Diplom_3\\pages\\login_page.py\", line 44, in click_recover_password_button\n    self.wait_for_element_visible(self._RECOVER_PASSWORD_BUTTON)\n  File \"C:\\Users\\Галина\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Галина\\Documents\\Yandex_praktikum\\Diplom\\Diplom_3\\Diplom_3\\pages\\base_page.py\", line 44, in wait_for_element_visible\n    WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located(locator))\n  File \"C:\\Users\\Галина\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Дождатся видимости элемента", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\Галина\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Галина\\Documents\\Yandex_praktikum\\Diplom\\Diplom_3\\Diplom_3\\pages\\base_page.py\", line 44, in wait_for_element_visible\n    WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located(locator))\n  File \"C:\\Users\\Галина\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "['xpath', './/a[text() = \"Восстановить пароль\"]']"}], "start": 1724618267843, "stop": 1724618288055}], "start": 1724618267843, "stop": 1724618288055}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1724618263675, "stop": 1724618288056, "uuid": "9b02fb1f-5746-465d-91cb-6b7c3a6754e6", "historyId": "7f59510e9ff7511751f0b3c6b6dacdb4", "testCaseId": "b1270fc541480d0d8e93e52fcd27d950", "fullName": "tests.test_password_recovery.TestRecoveryPage#test_cross_via_recovery_button", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_password_recovery"}, {"name": "subSuite", "value": "TestRecoveryPage"}, {"name": "host", "value": "LAPTOP-4UNN3S2K"}, {"name": "thread", "value": "20020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_password_recovery"}]}